### ISSUE TITLE
[Feature request] Automatic corpus generation

### ISSUE THREAD

**Issue by montyly** [trailofbits/test-fuzz#18]
It would be useful to have a `test-fuzz` flag to generate a minimal corpus (when there is no corpus). 

We can use the min/max/middle of each type, and a couple of usefull cases (1, 10, ..)

**Comment by smoelius** [comment]
This is a good idea.

Aside: `test-fuzz` will already try to generate one corpus entry when all arguments' types implement the `Default` trait. (This fact is not documented. :/)

That is, the macro's expansion includes a test named `default` that, when run, either does nothing or generates one corpus entry.

The relevant code is here (though it's not that easy to read :/ :/):
https://github.com/trailofbits/test-fuzz/blob/de7f02de32ec8edaaec6519db0c154d4efb4de90/macro/src/lib.rs#L454-L473

Expanding this functionality as you've described is certainly a good idea.

Relevant: https://docs.rs/num-traits/0.2.6/num_traits/bounds/trait.Bounded.html

**Comment by smoelius** [comment]
> It would be useful to have a test-fuzz flag...

I have a question about how literally I should take your request. How significant is it that these corpus entries be generated by a flag?

To get the `default` entries that I described above, you have to run `cargo test`.

More specifically, the `test_fuzz` macro generates a test called `default`. When you run the `default` test, it writes a corpus entry to the corpus directory if each of the target's argument types implements the `Default` trait.

Would running `cargo test` (like now for the "default" entries) suffice to get these new corpus entries?

**Comment by montyly** [comment]
Yes if it can be done directly by `cargo test` it's probably better. 

Maybe we can add in the log some info, like: "`X` does not have the `Default` trait, so no default corpus was generated. Ensure that your tests cover enough values"
