### ISSUE TITLE
Improve fuzzing performance for variable-length types

### ISSUE THREAD

**Issue by maxammann** [trailofbits/test-fuzz#304]
test-fuzz currently uses bincode for serialization. This might be problematic because it is TLV ([Type–length–value](https://en.wikipedia.org/wiki/Type%E2%80%93length%E2%80%93value)): https://github.com/bincode-org/bincode/blob/trunk/docs/spec.md

I did a quick comparison between basic libfuzzer (cargo-fuzz) and test-fuzz. 

```
#[test_fuzz::test_fuzz]
fn impossible(string: String) {
    if string.len() > 1000 {
        process::abort();
    }
}
```

```
fuzz_target!(|data: &[u8]| {
    if let Ok(string) = String::from_utf8(data.to_vec()) {
        if string.len() > 1000 {
            process::abort();
        }
    }
});
```

cargo-fuzz took a few seconds, whereas test-fuzz takes 12 minutes.

The solution to this is to replace bincode with an encoding that does not use length fields, but uses magic values. The magic value should be passed to the fuzzer via a dictionary or seed inputs.

**Comment by smoelius** [comment]
> whereas test-fuzz takes 12 minutes.

Just to confirm, this was with `--persistent`?

**Comment by maxammann** [comment]
> Just to confirm, this was with --persistent?

yes, as far as I can remember I used persistent mode.

**Comment by 0xalpharush** [comment]
```
  -l cmplog_opts - CmpLog configuration values (e.g. "2ATR"):
                  1=small files, 2=larger files (default), 3=all files,
                  A=arithmetic solving, T=transformational solving,
                  X=extreme transform solving, R=random colorization bytes.
```
I came across a comment about using `-l AT` for TLV inputs but I'm not sure what it does or how effective it is

**Comment by maxammann** [comment]
I believe my measurements were off when I opened this issue. libfuzzer is also having a hard time. However the following testcase is found quickly by libfuzzer:

```
#![no_main]

use libfuzzer_sys::fuzz_target;
use std::process;
use std::slice;

fuzz_target!(|data: &[u8]| {
    if let Ok(string) = String::from_utf8(data.to_vec()) {
        if string.len() > 100 {
            if string.len() > 200 {
                if string.len() > 300 {
                    if string.len() > 400 {
                        if string.len() > 500 {
                            process::abort();
                        }
                    }
                }
            }
        }
    }
});
```

**Comment by maxammann** [comment]
Ok so this issue is not about TLV actually. I still suspect issues with the TLV encoding, however the above issue is because AFL++ is not really capable of finding such issues quickly because it increases file sizes slowly.

**Comment by maxammann** [comment]
Closing this as I believe implementing a more forgiving parser (e.g. using magic-byte separated values instead of a TLV encoding) is just a workaround of having more custom mutators.

Structured fuzzing is likely the way to go. The solution would be to implement custom mutators that can deal with TLV encoded formats like https://chromium.googlesource.com/chromium/src/+/main/testing/libfuzzer/libprotobuf-mutator.md
